### ISSUE TITLE
Test ne funkcionise za StringOperacije

### ISSUE THREAD

**Issue by dsheedes** [programiranje2fon/kolokvijum2zadatak4#2]
Cak i kada se koristi _varijanta_resenja.txt_, test izbacuje gresku:
Spisak NEUSPEŠNIH testova:

> 1. Test za metodu izbaciDuplikate: 
>  	Metoda ne izbacuje duplikate. expected:<[Pera, Mika, Zika][]
> > but was:<[Pera, Mika, Zika][
> ]
> >

**Comment by bojantomic** [comment]
Nisam uspeo da ponovim tu gresku. Iskopirao sam tekst resenja iz _varijanta_resenja.txt_ u klasu _ispravka_koda.StringOperacije_ i pokrenuo testove, i radi sve ok. Probao sam i rucno da testiram i opet je ok. da li mozete da mi posaljete Vas kod/projekat u kojem se pojavljivao problem?

**Comment by dsheedes** [comment]
> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

> Eclipse IDE for Java Developers
> Version: 2019-12 (4.14.0)
> Build id: 20191212-1212

![Screenshot_2](https://user-images.githubusercontent.com/7893622/74772508-6e72b180-5290-11ea-8f94-3adf79777ab2.jpg)

[ispravka_koda.zip](https://github.com/programiranje2fon/kolokvijum2zadatak4/files/4221382/ispravka_koda.zip)

**Comment by bojantomic** [comment]
Hvala na detaljima, problem je  bio u Javi 8 i u Windows-u, na Linux-u i Javi 10 sve radi ok. Stvar je u tome kako se na kojem OS intepretira znak za kraj reda. Sad bi trebal oda je ok i za Windows i za Linux i za Javu 8.

Uradite pull, i probajte sada.
